Repository AY2122S2-CS2103-F09-3/tp, pull requests merged in 2022-03, with the labels that each got.

#35 Implement insurance storage
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddInsuranceCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/InsuranceBook.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/insurance/Title.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/InsuranceBookStorage.java
  src/main/java/seedu/address/storage/JsonAdaptedInsurance.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRecord.java
  src/main/java/seedu/address/storage/JsonInsuranceBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableInsuranceBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
Labels: priority.High

#43 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation

#44 Add Insurance and Client UI display
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/ListInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/ListPersonCommand.java
  src/main/java/seedu/address/ui/InsuranceCard.java
  src/main/java/seedu/address/ui/InsuranceListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/InsuranceListCard.fxml
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, UI

#49 Fix style issues
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/java/seedu/address/logic/commands/DeleteInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecordCommand.java
  src/main/java/seedu/address/logic/commands/ListRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/AppointmentParserUtil.java
  src/main/java/seedu/address/logic/parser/DeleteAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/RecordParserUtil.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RecordBook.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/appointment/exceptions/AppointmentNotFoundException.java
  src/main/java/seedu/address/model/record/ClientID.java
  src/main/java/seedu/address/model/record/InsuranceID.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/record/StartDate.java
  src/main/java/seedu/address/model/record/UniqueRecordList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedRecord.java
  src/main/java/seedu/address/storage/JsonRecordBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAppointmentBook.java
  src/main/java/seedu/address/storage/JsonSerializableRecordBook.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/InsuranceDetailCard.java
  src/main/java/seedu/address/ui/PersonDetailCard.java
  src/main/java/seedu/address/ui/PersonListPanel.java
Labels: enhancement

#61 Fix delete client and records bugs
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/parser/AddRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/record/ClientID.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRecord.java
Labels: bug

#72 find insurance feature
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindInsuranceCommandParser.java
  src/main/java/seedu/address/model/insurance/TitleContainsKeywordsPredicate.java
Labels: bug, documentation, enhancement

#74 Implement Edit Insurance command and Improve UI
  src/main/java/seedu/address/logic/commands/EditInsuranceCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditInsuranceCommandParser.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/PersonDetailCard.java
  src/main/java/seedu/address/ui/RecordUnderPersonPanel.java
  src/main/java/seedu/address/ui/SmallRecordCard.java
Labels: type.Story, UI

#79 Fix UI bug
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/InsuranceCard.java
  src/main/java/seedu/address/ui/InsuranceDetailCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/InsuranceDetailCard.fxml
Labels: bug, enhancement

#82 Implement find and edit record
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/FindRecordCommandParser.java
  src/main/java/seedu/address/model/record/RecordContainsKeywordsPredicate.java
Labels: enhancement

#86 Implement Clear Record Command
  src/main/java/seedu/address/logic/commands/ClearRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: enhancement

#91 Add delete object testcase and Implement Sort Record Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecordCommand.java
  src/main/java/seedu/address/logic/commands/EditAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
  src/main/java/seedu/address/logic/commands/SortRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/SortRecordCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/RecordBook.java
  src/main/java/seedu/address/model/appointment/Description.java
  src/main/java/seedu/address/model/insurance/Insurance.java
  src/main/java/seedu/address/model/record/EndDate.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/record/StartDate.java
  src/main/java/seedu/address/model/record/UniqueRecordList.java
  src/main/resources/view/SmallRecordListCard.fxml
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/AddInsuranceCommandTest.java
  src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/AddRecordCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteInsuranceCommandTest.java
  src/test/java/seedu/address/logic/commands/DeletePersonCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteRecordCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/ListAppointmentHistoryCommandTest.java
  src/test/java/seedu/address/logic/commands/ListExpiredRecordCommandTest.java
  src/test/java/seedu/address/logic/commands/ListInsuranceCommandTest.java
  src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeletePersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
  src/test/java/seedu/address/logic/parser/PersonParserUtilTest.java
  src/test/java/seedu/address/testutil/TypicalIndexes.java
Labels: enhancement, testcase

#93 Create ListRecordCommandTest
  src/test/java/seedu/address/logic/commands/ListRecordCommandTest.java
Labels: testcase

#94 edit command tests
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jessicajacelyn.md
  docs/team/seksek13.md
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentDescriptorTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
Labels: testcase

#97 Complete EditInsuranceCommandTest and EditInsuranceDescriptorTest
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditAppointmentDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditInsuranceCommandTest.java
  src/test/java/seedu/address/logic/commands/EditInsuranceDescriptorTest.java
  src/test/java/seedu/address/testutil/EditAppointmentDescriptorBuilder.java
  src/test/java/seedu/address/testutil/EditInsuranceDescriptorBuilder.java
  src/test/java/seedu/address/testutil/InsuranceBuilder.java
Labels: testcase

#98 Update DG
  docs/DeveloperGuide.md
  docs/images/MainWindow.jpg
  docs/images/StorageClassDiagram.jpg
  docs/images/UIstructure.jpg
  src/main/resources/view/MainWindow.fxml
Labels: documentation

#99 Implement Test Cases for find appointment/insurance/record
  src/test/java/seedu/address/logic/commands/FindAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/FindInsuranceCommandTest.java
  src/test/java/seedu/address/logic/commands/FindRecordCommandTest.java
Labels: testcase

#108 Update DG
  docs/DeveloperGuide.md
  docs/images/Arch.png
  docs/images/ArchSequenceDiagram.png
  docs/images/StorageClassDiagram.png
Labels: documentation

#109 Update DG
  docs/images/ComponentManagers.png
Labels: documentation

#111 Added Table of Contents for DG
  docs/DeveloperGuide.md
  docs/images/ArchSequenceDiagram.png
Labels: documentation

#117 Update UserGuide
  docs/UserGuide.md
Labels: documentation

#116 Fix insurance display issue
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/PersonDetailCard.fxml
Labels: bug

#119 Update Userguide.md
  docs/UserGuide.md
Labels: documentation

#134 Edit all javadocs for commands
  src/main/java/seedu/address/logic/commands/AddInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/java/seedu/address/logic/commands/ClearInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/ClearPersonCommand.java
  src/main/java/seedu/address/logic/commands/ClearRecordCommand.java
  src/main/java/seedu/address/logic/commands/DeleteAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/DeleteInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecordCommand.java
  src/main/java/seedu/address/logic/commands/EditInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/logic/commands/FindAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/FindInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ListAppointmentHistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListExpiredRecordCommand.java
  src/main/java/seedu/address/logic/commands/ListInsuranceCommand.java
  src/main/java/seedu/address/logic/commands/ListRecordCommand.java
  src/main/java/seedu/address/logic/commands/SortAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/SortRecordCommand.java
Labels: documentation

#138 Improve UI
  bin/main/view/MainWindow.fxml
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  src/main/java/seedu/address/ui/ExpiredRecordCard.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatusBarFooter.java
  src/main/resources/view/AppointmentListPanel.fxml
  src/main/resources/view/CommandBox.fxml
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/InsuranceDetailCard.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ObjectDetailPanel.fxml
  src/main/resources/view/PersonDetailCard.fxml
  src/main/resources/view/PersonListCard.fxml
  src/main/resources/view/PersonListPanel.fxml
  src/main/resources/view/RecordDetailCard.fxml
  src/main/resources/view/RecordUnderPersonPanel.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/main/resources/view/SmallRecordListCard.fxml
  src/main/resources/view/StatusBarFooter.fxml
Labels: UI
