Repository AY2122S2-CS2103-F09-3/tp, pull requests merged in 2022-04, with the labels that each got.

#200 Fix insurance price cant be deciaml number
  docs/UserGuide.md
  src/main/java/seedu/address/model/insurance/Price.java
Labels: bug

#202 Fix UG issue related to insurance
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: documentation

#204 Fix help window UG link
  src/main/java/seedu/address/ui/HelpWindow.java
Labels: bug, UI

#210 Update UI class diagram on the removal of status bar
  docs/DeveloperGuide.md
  docs/images/UiClassDiagram.png
  docs/images/UiClassDiagramUpdated.png
Labels: documentation

#214 Add more words to glossary
  docs/DeveloperGuide.md
Labels: documentation

#215 Fix list history bug
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
Labels: bug

#224 Update seksek13.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/seksek13.md
Labels: documentation

#230 Update Manual Testing in DG
  docs/DeveloperGuide.md
Labels: documentation
